packages/riipen-ui-docs/src/pages/components/progress-bar/Colors.jsx
packages/riipen-ui-docs/src/pages/components/progress-bar/Unfilled.jsx
packages/riipen-ui-docs/src/pages/components/progress-bar/progress-bar.md
packages/riipen-ui/package.json
packages/riipen-ui/src/components/ProgressBar.jsx

Add unfilled prop and new warning color to progress bar needed for the new project pages
I think i did everything except bump the package version?

Add unfilled prop and new warning color to progress bar

---

packages/riipen-ui/src/components/Radio.jsx

All radio buttons on our site look like 💩 right now because our site is border-box but the ui demo site is content-box.
huge change
before:
after:

Fix radio buttons on border-box site

---

packages/riipen-ui-docs/src/pages/components-api/grid-item.md
packages/riipen-ui-docs/src/pages/components/form/Basic.jsx
packages/riipen-ui-docs/src/pages/components/form/Error.jsx
packages/riipen-ui-docs/src/pages/components/form/Group.jsx
packages/riipen-ui-docs/src/pages/components/grid/Grow.jsx
packages/riipen-ui-docs/src/pages/components/grid/grid.md
packages/riipen-ui/package.json
packages/riipen-ui/src/components/GridItem.jsx

Added Grid-Item with grow option to allow grid items to fill the full width of the grid.
Also fixed compilation error on forms
packages/riipen-ui/src/components/GridItem.jsx

Added flex-grow option to ui grid

---

packages/riipen-ui-docs/src/pages/components-api/menu.md
packages/riipen-ui-docs/src/pages/components-api/popover.md
packages/riipen-ui-docs/src/pages/components/popover/Demo.jsx
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Menu.jsx
packages/riipen-ui/src/components/MenuList.jsx
packages/riipen-ui/src/components/Popover.jsx

Updated the popover for the menu to be rendered as hidden in the top left corner until it is opened. 
This fixes the issue where the popover would not be in the correct position if it was initially positioned too far to the right of the screen
Turns out position: absolute combined with top and left attributes is 'smart' enough to make sure the width of the box is not more than the width of the view window. So I have positioned the box in the top left to start and then move it to the correct location when the popover is opened.

Popover fix

---

packages/riipen-ui/src/components/Menu.jsx

https://github.com/riipen/web/pull/2218
This fixes an issue where hitting enter in a textarea caused it to lose focus. I remove the keydown handler and just pass through the onClose prop 🎉 .
Let me know if there is some case that forwarding onClose to the popover won't cover. I thiiiink this seems good.. but 🤷‍♂ 
This bug was so hard to track down, mostly because of its intermittent behaviour. On some pages it happened, and then others it didnt.. wasn't affected by being outside of the react tree.. but messing with the entity reducer could get it to not trigger sometimes (totally by chance). Ultimately when anchorEl was null the bug didn't trigger.
Just happy I eventually found it 🙈 . We should try to be careful about window.addEventListener in the future and possibly try to remove …

[PLT-4851] Forward Menu onClose prop to Popover

---

packages/riipen-ui-docs/src/pages/components-api/menu-list.md
packages/riipen-ui-docs/src/pages/components-api/menu.md
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Menu.jsx
packages/riipen-ui/src/components/MenuList.jsx

Added proper handling for children. 
The components used to crash when only 1 child was provided as it is not handled as an array. Using the React.Children.map() works the way it was built to work
Might need to update a couple other places, ticket logged to search for those
packages/riipen-ui/src/components/MenuList.jsx

[PLT-4906] Menu Children

---

packages/riipen-ui/package.json
packages/riipen-ui/src/components/FormGroup.jsx
packages/riipen-ui/src/components/Input.jsx
packages/riipen-ui/src/components/InputHint.jsx
packages/riipen-ui/src/components/InputLabel.jsx

Updated InputLabels to be larger and gray.  Updated Input to have slightly smaller padding.  Updated FormGroup title and subtitle styling.
Not 100% sure whether I overrode the FormGroup styles correctly.
/components/form
/components/input

[PLT-4943]: Update input label, form group, and input styling

---

packages/riipen-ui-docs/src/pages/components-api/input-label.md
packages/riipen-ui-docs/src/pages/components-api/menu.md
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Menu.jsx
packages/riipen-ui/src/components/MenuList.jsx

Added click event to menu list div that emits null event
This is useful for menus that dont have indexes to know when an option in the menu has been selected

[PLT-4906] Emit click event even when menu variant is not selection

---

packages/riipen-ui/src/components/MenuList.jsx

* If a MenuList's children were wrapped in a React.Fragment, the 'color' prop was not being passed as expected
* Add `handleFragmentChildren()` to `getListItems`
/components/MenuList

add handleFragmentChildren

---

packages/riipen-ui-docs/src/pages/components/tooltip/Location.jsx
packages/riipen-ui/src/components/Tooltip.jsx

Update Tooltip to add fade in animation and keep tooltip on screen.  Update positions so that they are actually top-right = tooltip displays on top right (it was the opposite which was confusing).
Update example wording.
Tooltip

Update tooltip position, keep tooltip on screen, add fade animation

---

packages/riipen-ui/package.json

running `npm run build` on `riipen-ui` when `/web` had a `symlink` to `riipen-ui/build` caused `/web` server to crash on some machines. 
* This change causes `npm run build` not to run `rm -rf ./build` before building.
* Instead, build is made in `./temp`, then `./temp` is transferred to `./build`. 
* `./temp` is deleted afterwards
Thank you @kradical for investigating + solving this issue

fix build command to not crash web when rebuilt

---

packages/riipen-ui/package.json
packages/riipen-ui/src/components/Popover.jsx

Return empty string if not fullWidth so that popovers have the correct z-index.
components/Popover

[PLT-5037]: return empty string if not fullWidth

---

packages/riipen-ui-docs/src/pages/components/button/Contained.jsx
packages/riipen-ui-docs/src/pages/components/button/Outlined.jsx
packages/riipen-ui-docs/src/pages/components/button/Text.jsx
packages/riipen-ui/src/components/Button.jsx

-Added line height so that buttons with/without icons are the same height
-Decreased the padding of outlined buttons by 1 px to accommodate the 1 px border
-Updated the spacing to some buttons in the examples
There's still one really pesky thing going on with buttons with icons: buttons with an iconStart prop display slightly higher than other buttons.  I _think_ something is going on with the flex container, but still can't quite pinpoint the behaviour.  See attached screenshot and also https://ui.riipen.com/components/button/#icons.

Make buttons the same size

---

packages/riipen-ui/package.json
packages/riipen-ui/src/components/MenuItem.jsx

* border-left on dropdown items should be 3px (from navbar redesign)
[PLT-4595](https://riipen.atlassian.net/browse/PLT-4595?focusedCommentId=21349&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21349)
3px border-left

[PLT-4595]: decrease border-left to 3px

---

packages/riipen-ui/src/components/Tooltip.jsx

Move passing props to the Popover in the Tooltip component to allow for some overrides.  Also fix an issue with whitespace and the tooltip arrows.
/components/Tooltip

Update tooltip visibility

---

packages/riipen-ui/package.json
packages/riipen-ui/src/components/ButtonIcon.jsx

Relates to [[PLT-5120]](https://riipen.atlassian.net/browse/PLT-5120)
* Add outline prop to `ButtonIcon` to improve accessibility
* Required for https://github.com/riipen/web/pull/2475
* Bump package version
* Should likely have this default to true so that all `ButtonIcon` components are accessible, but have put as false for now until discussion determines we want all `ButtonIcon` components to have outline by default

[PLT-5120]: Add outline prop to ButtonIcon

---

packages/riipen-ui-docs/src/pages/components-api/button-icon.md
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Checkbox.jsx
packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/Tabs.jsx

Fixed issue where menu items were not keyboard accessible
Fixed issue where outline for checkboxes was not appearing
Learned lots about a11y attributes... also, turns out you use space to toggle checkboxes... not enter
Menus:
Checkboxes:

[PLT-5122] Added accessibility attributes to tabs and checkboxes

---

packages/riipen-ui/src/components/ListItem.jsx
packages/riipen-ui/src/components/MenuItem.jsx

[RB-1571](https://rollbar.com/riipen/web/items/1571/)
[[PLT 5370]](https://riipen.atlassian.net/browse/PLT-5370)
* Error occurs when `stopPropagation()` is called on `event` when `event` is `undefined`
* Pass `event` from `ListItem` to `handleClick` in `MenuItem`

[PLT 5370 / RB-1571]: Fix undefined event error

---

README.md
packages/riipen-ui/scripts/update_version.sh

Added a script to perform the tasks needed to update and release a new version of the UI
The steps include:
1) Validate the branch (can only be run on staging or master)
2) Update the npm version
3) Push updated package files to git
4) Tag Commit with new version number
5) Build the local files
6) Publish the build to npm
packages/riipen-ui/scripts/update_version.sh

Added version update script that detects branch

---

packages/riipen-ui/src/components/Popover.jsx
packages/riipen-ui/src/components/Tooltip.jsx
packages/riipen-ui/src/utils/container.js
packages/riipen-ui/src/utils/index.js

[[PLT-5265]](https://riipen.atlassian.net/browse/PLT-5265)
* Fix bug with `Popover` where initial position would be off by (properContentRectWidth/2 - 21px)
* Add `keydown` handler to `Popover` / `Tooltip`
* Add `closeOnParentScroll` prop to `Popover` --> closes Popover when scrollable Parent container is scrolled
* Add `getClosestScrollableParent` util
* Add ability for `Tooltip` open/close state to be controlled by props
* Required for https://github.com/riipen/web/pull/2585

[PLT-5265] Popover, Tooltip improvements

---

packages/riipen-ui/src/components/Popover.jsx

* change default `isOpen` prop to `true`, fixes Invite Students /  `Students/Header` popover not appearing issue

Students/Header Popover issue fix

---

packages/riipen-ui-docs/src/pages/components/tabs/Forced.jsx
packages/riipen-ui-docs/src/pages/components/tabs/tabs.md
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/Tabs.jsx

Using this for nested tabs where the values dont always match (such as using window.location for the value)

Allow tabs to be forced to display active

---

packages/riipen-ui/src/components/EditorBlockStyleControls.jsx
packages/riipen-ui/src/components/EditorInlineStyleControls.jsx

https://github.com/riipen/developer-web/pull/71
This makes it so that only the icons used are imported instead of the whole library (700kb parsed) 🎉 .
This will probably help out platform too because hopefully we are using the proper import style everywhere on that project.

Import specific fontawesome icons instead of all

---

packages/riipen-ui-docs/src/pages/components/avatar/Image.jsx
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Avatar.jsx

There is currently an issue with the UI kit avatar where if there is an avatar with an image and an avatar with just letters (or other content), they do not display nicely next to each other.  This PR attempts to solve this issue by updating the css in the Avatar component.
Original issue: 
packages/riipen-ui/src/components/Avatar.jsx

Add span wrapper around img avatars

---

packages/riipen-ui/src/components/Avatar.jsx

Small update image height so image fits within wrapper span contents.
packages/riipen-ui/src/components/Avatar.jsx

Update avatar image height

---

packages/riipen-ui-docs/src/pages/components/tabs/Breakpoint.jsx
packages/riipen-ui-docs/src/pages/components/tabs/tabs.md
packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/Tabs.jsx

Update tabs styling to have dividers and smaller font between them at a designated breakpoint.
-add breakpoint prop
-add examples
packages/riipen-ui/src/components/Tabs.jsx

Add horizontal tab mobile styling

---

packages/riipen-ui-docs/pages/components-api/container-header.jsx
packages/riipen-ui-docs/src/pages/components-api/container-header.md
packages/riipen-ui-docs/src/pages/components/container/Border.jsx
packages/riipen-ui-docs/src/pages/components/container/Colors.jsx
packages/riipen-ui-docs/src/pages/components/container/Headers.jsx
packages/riipen-ui-docs/src/pages/components/container/container.md
packages/riipen-ui/src/components/Container.jsx
packages/riipen-ui/src/components/ContainerHeader.jsx

Add ContainerHeader component that gives containers a coloured header.
Update Container component to have colour, border, and header options.
Convert Container to functional component.
components/ContainerHeader
components/Container - last commit converts to functional component.

Add ContainerHeader component

---

packages/riipen-ui/src/components/MenuList.jsx

Error on dashboard when user is traversing the menu using keyboard inputs
[rollbar #1812](https://rollbar.com/riipen/platform-web/items/1812/)
Was unable to duplicate the error so I just added safety checks to make sure the component doesnt crash
packages/riipen-ui/src/components/MenuList.jsx

Fixed error when menu item used improperly

---

packages/riipen-ui-docs/pages/components-api/vertical-progress-bar.jsx
packages/riipen-ui-docs/pages/components/vertical-progress-bar.jsx
packages/riipen-ui-docs/src/pages.js
packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/Color.jsx
packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/Content.jsx
packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/Icon.jsx
packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/vertical-progress-bar.md
packages/riipen-ui/src/components/VerticalProgressBar.jsx
packages/riipen-ui/src/components/VerticalProgressBarItem.jsx

_[Jira Ticket: [PLT-5814]](https://riipen.atlassian.net/browse/PLT-5814)_
The `ProgressBarVertical` component implemented [here](https://github.com/riipen/platform-web/pull/2986) by @ksmort needed to be added to the UI-Kit.
To be honest I floundered quite a bit troubleshooting the CSS and figuring out that some of it wasn't being picked up by the `Grid` component. I ended up using `linkedStyles` to make it happen once I got some assistance.
For the most part I tried to mirror other components and could use some context as to what this achieves:
```
export default withClasses(VerticalProgressBarItem);
```
I wrote pretty small commits in case I really need to change things in multiple places.

[PLT-5814] Add VerticalProgressBar to the UI-Kit

---

packages/riipen-ui/src/components/RadioButtonGroup.jsx
packages/riipen-ui/src/components/RadioGroup.jsx

1. Removed `<fieldset>` padding from radio components
We never want margin / padding around core UI elements as when you go to insert them into a page, you then have to fight that with additional `classes` almost all the time.

Fieldset Padding

---

packages/riipen-ui-docs/src/pages/components-api/editor.md
packages/riipen-ui/src/components/Editor.jsx

design:
Main changes:
No border - use colour difference instead
Ability to add left justified actions
Ability to add control row full height actions
Have to update a couple places the editor is used on the web app where the prop naming has changed, but other than that its a minor change

Update editor styles to match new designs

---

packages/riipen-ui-docs/src/pages/components/chip/Click.jsx
packages/riipen-ui-docs/src/pages/components/chip/Hover.jsx
packages/riipen-ui-docs/src/pages/components/chip/Icon.jsx
packages/riipen-ui-docs/src/pages/components/chip/chip.md
packages/riipen-ui/src/components/Chip.jsx

Add section to Chip page for `onClick` prop.
Update the icon section to use `icon` prop instead of `iconStart`.
Added in the hover support.
Not 100% on what colour we want the hover to be, maybe checkout the branch and do a look?
Also a TODO: convert to function component.
91 packages/riipen-ui/src/components/Chip.jsx

Update hover functionality in Chip component

---

packages/riipen-ui-docs/src/pages/components-api/chip.md
packages/riipen-ui-docs/src/pages/components-api/editor.md
packages/riipen-ui/src/components/Editor.jsx

* Add prop to not `display: none` controlRow when on mobile
* web -> Message/Form/New shouldn't hide the control row when on mobile https://github.com/riipen/platform-web/pull/3393

[PLT-6474] Editor: mobileControlRow prop

---

packages/riipen-ui/src/components/MenuList.jsx

https://riipen.atlassian.net/secure/RapidBoard.jspa?rapidView=6&projectKey=PLT&modal=detail&selectedIssue=PLT-4638
The `MenuList` component crashes when passed an `undefined` item. This is a problem when we try to do something like `{course.school && .. Menu}` (or something like that) and `course.school` is `undefined`. We would like a case for this in `Menu` rather than at the higher level in platform-web. 
We need to simply not render the undefined item. This is much more graceful than crashing the entire page.
The crash happens when a clone is attempted on the React element in question, being the list item. When the child is undefined, it attempts to clone undefined which is not a React element.
Easily enough to replicate this you just have to do something like:
```js
<Menu> …
```

[PLT-4638] Add check to MenuList component for undefined child

---

packages/riipen-ui/src/components/Chip.test.jsx

updated default props test to use `props().propName` instead of `hasClass(className)`
Chip.test.jsx

[PLT-6633]Unit test for Chip

---

.circleci/config.yml
jest.config.js
package-lock.json
package.json
packages/riipen-ui-docs/package-lock.json
packages/riipen-ui-docs/package.json
packages/riipen-ui-docs/scripts/buildAPI.js
packages/riipen-ui/jest.config.js
packages/riipen-ui/package-lock.json
packages/riipen-ui/package.json

Seems like upgrading to npm 7 and re running the install causes a few issues. I did a few things here to get things working again.
1. Upgraded react-docgen
2. Added a check to skip test files / snapshots when building for react-docgen
3. Updated the jest config to look in the src dir so it doesnt pick up files from a build
4. Removed some dependency warnings
5. Updated (and fixed) the required npm engine in both packages

Fix build and update dependiecies

---

packages/riipen-ui/src/components/Checkbox.jsx
packages/riipen-ui/src/components/Checkbox.test.jsx
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap

Checkboxes can be set as checked when they are tabbed to and when Enter is pressed.
Thanks Carmen for help with the event!
Checkbox.jsx

[PLT 5638] Additional event functionality for Checkbox

---

packages/riipen-ui/src/components/Checkbox.jsx
packages/riipen-ui/src/components/Checkbox.test.jsx
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap

Outline now appears in Firefox when Checkbox is tabbed to. Let me know if there are further style changes needed.
Checkbox.jsx

Firefox style change to make outline visible on tab event

---

packages/riipen-ui-docs/src/pages/components/button/Icons.jsx
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Button.jsx
packages/riipen-ui/src/components/Button.test.jsx

Allow the button to render icons directly instead of having to pass a component in

Allow buttons to take icons and components that render icons

---

packages/riipen-ui-docs/src/pages/components/rich-text-editor/Usage.jsx
packages/riipen-ui/src/components/Editor.jsx
packages/riipen-ui/src/components/RichTextEditor.jsx

Added max height and scroll bar to stop text overflow.
packages/riipen-ui/src/components/Editor.jsx

[PLT-7175] Add scroll bar to Editor text area

---

package.json
packages/riipen-ui-docs/src/pages/components/typography/Color.jsx
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Typography.jsx
packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap

Add warning colour for Typography.
packages/riipen-ui/src/components/Typography.jsx

Add typography warning colour

---

packages/riipen-ui-docs/src/pages/components/typography/Color.jsx
packages/riipen-ui/package-lock.json
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Typography.jsx
packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap

Add 'disabled' color option to Typography.
packages/riipen-ui/src/components/Typography.jsx

Add Typography disabled colour

---

packages/riipen-ui/src/components/InputLabel.jsx
packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap

New designs call for input labels to have #373737 color,
add grey as an option for our input labels.

[PLT-7203]: Add grey color to InputLabel

---

packages/riipen-ui-docs/src/pages/components/input/Variant.jsx
packages/riipen-ui-docs/src/pages/components/input/input.md
packages/riipen-ui/src/components/Input.jsx
packages/riipen-ui/src/components/Input.test.jsx
packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap

Add new `variant` prop that styles the Input component.
The `default` variant is the current styling.  The `underlined` variant displays only an underline.
Update tests and snapshots.

Add Underlined and Default Input variants

---

packages/riipen-ui-docs/src/pages/components/input/Icon.jsx
packages/riipen-ui-docs/src/pages/components/input/input.md
packages/riipen-ui/src/components/Input.jsx
packages/riipen-ui/src/components/Input.test.jsx
packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap

Add icon prop to Input component. This renders an icon on the left side of the input.  Also update icon sizes based on `size` prop.
Update docs and tests.
Open to adding support for flexibility of icons on either right or left side.
Based off https://github.com/riipen/ui/pull/187.

Add icon prop to Input

---

packages/riipen-ui-docs/src/pages/components/input/Icon.jsx
packages/riipen-ui-docs/src/pages/components/input/Size.jsx
packages/riipen-ui-docs/src/pages/components/input/Variant.jsx
packages/riipen-ui-docs/src/pages/components/input/input.md
packages/riipen-ui/src/components/Input.jsx
packages/riipen-ui/src/components/Input.test.jsx
packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap

Add `size` prop to Input component.  This prop changes the padding inside the input.
Update tests and docs.

Add Input size prop

---

packages/riipen-ui-docs/src/pages/components/input/Meta.jsx
packages/riipen-ui-docs/src/pages/components/input/input.md
packages/riipen-ui/src/components/Input.jsx
packages/riipen-ui/src/components/Input.test.jsx
packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap

Add `meta` prop to Input. This displays things on the bottom right of the Input field.
Update some logic with rendering error/warning, so that it works nicely with meta.
Update tests/docs.

Add meta prop to Input component

---

packages/riipen-ui/src/components/Badge.jsx
packages/riipen-ui/src/components/__snapshots__/Badge.test.jsx.snap

Adding justify-content: flex-end allows us to use badge
around an avatar that is part of a Grid
(such as for platform-web/Layout/Wizard/Steps/Icon). Adding this property
does not appear to adversely affect other Badges on the platform.
(Tested with NavbarMessages badge).
Before
After

[PLT-7434] Add justify-content: flex-end to Badge .root

---

packages/riipen-ui-docs/src/pages/components/rich-text-editor/Usage.jsx
packages/riipen-ui/package.json
packages/riipen-ui/src/components/Editor.jsx
packages/riipen-ui/src/components/EditorDecorator.jsx
packages/riipen-ui/src/components/EditorUtils.jsx
packages/riipen-ui/src/components/EditorUtils.test.jsx
packages/riipen-ui/src/components/index.js

Add EditorUtils, collection of editor content manipulation functions.
Small Updates to RTE.
These for sure could live on the web, ive opted to move them here as they directly work with draft js objects. Once we do this the frontend no longer needs draft-js or draft-convert as dependencies

Add EditorUtils various util functions for editor manipulation

---

packages/riipen-ui/src/components/Tooltip.jsx

Update small tooltip top/bottom padding to be a bit smaller.

Update tooltip top/bottom padding to be a bit smaller in small size

---

packages/riipen-ui/src/components/Editor.jsx

Updating the placeholder input text colour  to `grey400` in Rich Text Editors to be consistent with `platform-web`
Original PR: https://github.com/riipen/platform-web/pull/4140

[PLT-7482] Update default input placeholder text colour for Editor

---

.gitignore
packages/riipen-ui/src/components/Editor.jsx

This is part of this [ticket](https://riipen.atlassian.net/browse/PLT-7426) for trimming whitespace in our inputs. The idea is we trim whitespace when the input is out of focus. In order to do this, we need onBlur event to be triggered on our rich text editor.

Pass onBlur prop to Draftjs in Editor component

---

packages/riipen-ui/.prettierrc
packages/riipen-ui/src/components/Avatar.jsx
packages/riipen-ui/src/components/__snapshots__/Avatar.test.jsx.snap

* Add a `color` prop to `<Avatar>`, defaults to "grey" and can be one of "grey" or "white"
* required for https://github.com/riipen/platform-web/pull/4242
Avatar with background white, others with default grey background

[PLT-7534] Add color prop to Avatar

---

packages/riipen-ui/src/components/InputLabel.jsx
packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap

Update InputLabel to have default fontWeight = medium and color = greyA400
src/components/InputLabel.jsx

Update InputLabel default color to greyA400 and font weight medium

---

packages/riipen-ui/src/components/Tooltip.jsx

Blur was stealing the focus from Samsung keyboard, so yeet it outta here.
components/Tooltip

Remove blur to stop focus stealing

---

packages/riipen-ui-docs/src/modules/components/MarkdownPage.jsx
packages/riipen-ui-docs/src/modules/components/Menu.jsx

Add Menu for "mobile" view, as the left-hand menu disappears at smaller screen sizes.
Mostly a  proof of concept PR, definitely needs more work and cleaning up.
Mostly a  proof of concept PR, definitely needs more work and cleaning up.
packages/riipen-ui-docs/src/modules/components/MarkdownPage.jsx

Mobile menu for UI Riipen page

---

packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/Color.jsx
packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/Content.jsx
packages/riipen-ui-docs/src/pages/components/vertical-progress-bar/Icon.jsx
packages/riipen-ui/src/components/VerticalProgressBar.jsx
packages/riipen-ui/src/components/VerticalProgressBar.test.jsx
packages/riipen-ui/src/components/VerticalProgressBarItem.jsx
packages/riipen-ui/src/components/VerticalProgressBarItem.test.jsx
packages/riipen-ui/src/components/__snapshots__/VerticalProgressBar.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/VerticalProgressBarItem.test.jsx.snap

Update VerticalProgressBar to use inversion of control and accept VerticalProgressBarItems as children, rather than using the `progresses` prop.
Add unit tests for VerticalProgressBar/VerticalProgressBarItem.
Some minor clean up.
Small styling edits to make the icon circle slightly smaller, and decrease the margin from the icons to the content.
VerticalProgressBar

Update VerticalProgressBar to accept VerticalProgressBarItems as children

---

packages/riipen-ui/src/components/Input.jsx

Update label prop type to be node.

Make label prop of type node

---

packages/riipen-ui/src/components/InputLabel.jsx
packages/riipen-ui/src/components/InputLabel.test.jsx
packages/riipen-ui/src/components/RadioGroup.jsx
packages/riipen-ui/src/components/RadioGroup.test.jsx
packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap

We are updating the Project Wizard to include descriptive Tooltips. Similar to how `FormGroup` was updated in `platform-web` to include the tooltip as a prop, we should update RadioGroup so it can pass a tooltip node.
Related PR: [Project Library Tooltips](https://github.com/riipen/platform-web/pull/4609)
Added in text to show placement of where the tooltip would go

[PLT-8224] Add tooltip prop to RadioGroup

---

packages/riipen-ui/src/components/Typography.jsx
packages/riipen-ui/src/components/__snapshots__/Badge.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Button.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/ButtonIcon.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Chip.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Link.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/ListItem.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/MenuItem.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/MenuList.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/TableCell.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/TableHeaderCell.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap
packages/riipen-ui/src/themes/default.js

https://riipen.atlassian.net/browse/PLT-8331
Add mobile Typography sizes and line-height, update `Typography` component to use these sizes on mobile resolution
Sizes: https://www.figma.com/file/RYjBuSngR9y0L5PeDZp6b2/01-Components?node-id=1725%3A373664

[PLT-8331] Update typography sizes and add mobile sizes

---

packages/riipen-ui-docs/src/pages/components/typography/WordBreak.jsx
packages/riipen-ui-docs/src/pages/components/typography/typography.md
packages/riipen-ui/src/components/Typography.jsx
packages/riipen-ui/src/components/Typography.test.jsx
packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap

Add wordBreak prop to Typography.
Update tests and documents.
components/Typography

Add word break prop to typography

---

packages/riipen-ui/src/components/Typography.jsx
packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap

Update defaultProps to make wordBreak optional to debloat things.
packages/riipen-ui/src/components/Typography.jsx

Make wordBreak optional

---

packages/riipen-ui/src/components/RadioButton.jsx

Change RadioButton typography variant to be `body3` since some desktop sizes increased and this is equivalent to the previous `body2` size

[PLT-8331] Fix `RadioButton` typography on desktop

---

packages/riipen-ui/src/components/Accordion.jsx
packages/riipen-ui/src/components/__snapshots__/Accordion.test.jsx.snap

We want to enable AccordionDetails to be able to
access the Accordion context so that AccordionDetails
and its children can know whether or not their
Accordion is expanded. This can be used so that
we only load data when the accordion is expanded.

[PLT-9020] Wrap AccordionDetails in AccordionContext

---

packages/riipen-ui-docs/src/pages/components/tabs/TextTransform.jsx
packages/riipen-ui-docs/src/pages/components/tabs/tabs.md
packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/Tab.test.jsx
packages/riipen-ui/src/components/Tabs.jsx
packages/riipen-ui/src/components/Tabs.test.jsx
packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/Tabs.test.jsx.snap

Add textTransform prop to tabs to allow for different casing types.
src/components/Tab
src/components/Tabs

Add text transform to tabs

---

packages/riipen-ui-docs/src/pages/components/tabs/LetterSpacing.jsx
packages/riipen-ui-docs/src/pages/components/tabs/tabs.md
packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/Tab.test.jsx
packages/riipen-ui/src/components/Tabs.jsx
packages/riipen-ui/src/components/Tabs.test.jsx
packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap

Add letterSpacing prop to tabs.  Reason behind this is that we use custom styling to set the letter spacing to smaller on our site, so might as well bake it into tabs to DRY it up.  I can provide examples where we use it if needed.
src/components/Tab
src/components/Tabs

Add letterSpacing prop

---

packages/riipen-ui/scripts/release.sh

Update the release script so that we can automatically deploy new changes to the docs webpage
Discussion around this came out during the recent [retro](https://trello.com/c/uN2mOmcc/8-publish-docs-during-publish-script-for-ui-kit)
`packages/riipen-ui/scripts/release.sh`

Update docs webpage whenever new version of UI kit is released

---

packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/Tab.test.jsx
packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap

Update Tab to allow icons of type node.
src/components/Tab

Allow tab to be prop type node

---

packages/riipen-ui/src/components/Tooltip.jsx
packages/riipen-ui/src/components/__snapshots__/Tooltip.test.jsx.snap

Add border-width and calculated margin-top to Tooltip bottom arrow position to make it look better
Is a small change but looks prettier
Before:
After:

Improve tooltip arrow bottom position

---

packages/riipen-ui/src/components/Tab.jsx
packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap

- Add Tab label mobile font size, applicable for horizontal and vertical tabs
- Update vertical Tabs padding to adjust to mobile res

[PLT-9035] aditional fixes to typography sizes on mobile

---

packages/riipen-ui/src/components/Checkbox.jsx
packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap

Adjusted checkboxes to be thinner and centre aligned with text
Before:
After:

[PLT-9470] Adjusted checkbox weight and alignment

---

packages/riipen-ui/src/components/RadioButton.jsx
packages/riipen-ui/src/components/RadioButton.test.jsx
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap

Add wrapperProps to RadioButton so we can pass props to the wrapper div.  Thought about having `inputProps` instead but it would be a breaking change for radio button.

Add id prop to RadioButton

---

packages/riipen-ui/src/components/RadioButtonGroup.jsx
packages/riipen-ui/src/components/RadioButtonGroup.test.jsx
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap

Add `fullWidth` prop to radio button group to enable to buttons to stretch across the full div.
src/components/RadioButtonGroup.jsx

Add full width option to radio buttons

---

packages/riipen-ui/src/components/Editor.jsx

Add `forceFocus` prop to editor so that we can disable forcing focus on click if needed.
src/components/Editor.jsx

Add forceFocus prop to Editor component

---

packages/riipen-ui/src/components/RadioButton.jsx
packages/riipen-ui/src/components/RadioButtonGroup.jsx
packages/riipen-ui/src/components/RadioButtonGroup.test.jsx
packages/riipen-ui/src/components/Typography.jsx
packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap

Part 2 to https://github.com/riipen/ui/pull/279
Pass `fullWidth` through to RadioButton so that radio button option labels are not constrained by either current `min-width` styling.
src/components/RadioButton
src/components/RadioButtonGroup

Pass through fullWidth to RadioButton to remove min width on label

---

packages/riipen-ui/src/components/Editor.jsx

Add `componentDidUpdate` for `autoFocus` prop to force focus on editor if the prop changes.
src/components/Editor.jsx

Focus editor if autoFocus changes
