- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Popover.jsx
Updated Default margin threshold
Only applies to menus with the 'keepOnScreen' prop
Forgot to reset this value after some testing
> Updated default margin threshold

- packages/riipen-ui-docs/package-lock.json
- packages/riipen-ui-docs/package.json
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Button.jsx
Had to do some weirdness with height and margins as increasing the icon size made the buttons sit weird... (see screenshots) if you know a better way to do this or have seen something similar before hit me up
before
after
> Update button and icon size

- packages/riipen-ui-docs/src/pages/components-api/button-icon.md
- packages/riipen-ui-docs/src/pages/components-api/button.md
- packages/riipen-ui-docs/src/pages/components-api/grid-item.md
- packages/riipen-ui-docs/src/pages/components-api/grid.md
- packages/riipen-ui-docs/src/pages/components-api/link.md
- packages/riipen-ui-docs/src/pages/components-api/popover.md
- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/MenuItem.jsx
Made menu items show bar on hover, not just when selected
Also updated some ui docks
packages/riipen-ui/src/components/MenuItem.jsx
> Made menu item show left border when hovered

- packages/riipen-ui-docs/src/pages/components/badge/Color.jsx
- packages/riipen-ui-docs/src/pages/components/badge/badge.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Badge.jsx
> Add muted badge colour

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/FormGroup.jsx
- packages/riipen-ui/src/components/InputLabel.jsx
Fix typo with InputLabel font size and add more specificity to form group styles so that styles actually get applied.
FormGroup and InputLabel components.
> Fix label font size and form group styling

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Radio.jsx
- packages/riipen-ui/src/components/RadioGroup.jsx
Update radio button styling:
-make radio buttons smaller and change the colours of the dots
-change default label colour to secondary text colour
-change styling of disabled radio button
-update labels so that when radio button is selected, the label colour changes to the theme colour
/components/radio
> [PLT-4960]: update radio button styling and update label spacing

- packages/riipen-ui-docs/src/pages/components-api/input-label.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Input.jsx
- packages/riipen-ui/src/components/InputLabel.jsx
- packages/riipen-ui/src/components/RadioGroup.jsx
Added hint prop to InputLabel so that margins can be automatically configured.  Removed marginBottom prop.  Updated components using InputHint.
components/Input and components/Radio
> Add hint prop to InputLabel

- packages/riipen-ui-docs/src/pages/components/table/Expandable.jsx
- packages/riipen-ui-docs/src/pages/components/table/Mobile.jsx
- packages/riipen-ui-docs/src/pages/components/table/table.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/TableGenerator.jsx
- packages/riipen-ui/src/components/TableRow.jsx
This is what i eventually landed on. Basically just pass a function to determine which rows to display expanded or not. Originally i had it as an attribute on the entity, but dont think modifying the entity is ideal
> Add expandable row to tableGenerator

- packages/riipen-ui-docs/pages/components-api/tooltip.jsx
- packages/riipen-ui-docs/pages/components/tooltip.jsx
- packages/riipen-ui-docs/src/pages.js
- packages/riipen-ui-docs/src/pages/components-api/tooltip.md
- packages/riipen-ui-docs/src/pages/components/tooltip/Color.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/Component.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/Location.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/Visibility.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/tooltip.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Tooltip.jsx
- packages/riipen-ui/src/components/index.js
Create Tooltip component based on Popover.  This Tooltip component has little arrows based on the contentPosition prop.  There are also colour options.
Definitely need help on the description for the tooltips, I'm very bad at that!
TODO: animation transitions, other things I might have missed
components/Tooltip
> Add tooltip component

- packages/riipen-ui/README.md
I was debugging some local stuff and thought might as well add some setup instructions here!
> Add local development instructions

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/TableGenerator.jsx
- packages/riipen-ui/src/components/TableRow.jsx
Updated mouse over and out to enter and leave
over and out run the function every time the mouse moves inside the dom element
enter and leave only run when the mouse passes the borders of the element
> Changed over and out to enter and leave

- packages/riipen-ui-docs/src/pages/components/tooltip/Color.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/Size.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/Visibility.jsx
- packages/riipen-ui-docs/src/pages/components/tooltip/tooltip.md
- packages/riipen-ui/src/components/Tooltip.jsx
Add size prop to tooltip.
Update animation so that it works properly (there was some weirdness going on).
Some general clean up.
/components/tooltip
> Tooltip clean up

- packages/riipen-ui-docs/src/pages/components-api/menu.md
- packages/riipen-ui-docs/src/pages/components-api/popover.md
- packages/riipen-ui-docs/src/pages/components-api/table-cell.md
- packages/riipen-ui-docs/src/pages/components-api/table-generator.md
- packages/riipen-ui-docs/src/pages/components-api/table-row.md
- packages/riipen-ui-docs/src/pages/components-api/table.md
- packages/riipen-ui-docs/src/pages/components-api/tooltip.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Table.jsx
- packages/riipen-ui/src/components/TableBody.jsx
- packages/riipen-ui/src/components/TableCell.jsx
- packages/riipen-ui/src/components/TableGenerator.jsx
- packages/riipen-ui/src/components/TableHeader.jsx
- packages/riipen-ui/src/components/TableRow.jsx
- Changed table background to match designed
- Added ability to add a rowClick callback to the generated table
- Removed padding from expanded row
- Added padding prop to TableRow
packages/riipen-ui/src/components/TableGenerator.jsx
> Table Generator Update

- packages/riipen-ui/src/components/ButtonIcon.jsx
Update ButtonIcon's default colour.  Also update default button to be orange on hover.  Added "muted" colour so that there is a gray button that hovers on gray.
components/Button
> [PLT-5048]: Update button icon hover and default colour

- packages/riipen-ui-docs/src/pages/components-api/button.md
- packages/riipen-ui-docs/src/pages/components/button/Inverted.jsx
- packages/riipen-ui-docs/src/pages/components/button/button.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Button.jsx
Added inverted button type for Search Page Header
packages/riipen-ui/src/components/Button.jsx
> [PLT-5158] Added inverted button type

- packages/riipen-ui-docs/package.json
- packages/riipen-ui-docs/src/pages/components-api/button.md
- packages/riipen-ui-docs/src/pages/components-api/popover.md
- packages/riipen-ui-docs/src/pages/components-api/tooltip.md
- packages/riipen-ui-docs/src/utils/generateAPIMarkdown.js
- packages/riipen-ui/src/components/Button.jsx
- packages/riipen-ui/src/components/ButtonIcon.jsx
- packages/riipen-ui/src/components/Checkbox.jsx
- packages/riipen-ui/src/components/Input.jsx
- packages/riipen-ui/src/components/Link.jsx
- packages/riipen-ui/src/components/ListItem.jsx
- packages/riipen-ui/src/components/MenuItem.jsx
- packages/riipen-ui/src/components/Tab.jsx
- packages/riipen-ui/src/utils/index.js
- packages/riipen-ui/src/utils/useIsFocusVisible.js
- packages/riipen-ui/src/utils/withThemeContext.jsx
Converted a bunch of components to function components
Added accessibility styles for any component that can have actions associated with it
Added new withThemeContext HOC
Small Web PR as well: [Web PR](https://github.com/riipen/web/pull/2600)
When using tab to navigate:
When clicking:
packages/riipen-ui/src/components/Button.jsx
packages/riipen-ui/src/utils/useIsFocusVisible.js
> [PLT-5373] Accessibility styles

- packages/riipen-ui-docs/src/pages/components/chip/Colors.jsx
- packages/riipen-ui-docs/src/pages/components/chip/Variants.jsx
- packages/riipen-ui/src/components/Chip.jsx
1. added a dark colour to the chip.
If you can think of a better name im down
> [PLT-5447] Add dark colour to chip

- packages/riipen-ui-docs/src/pages/components-api/form.md
- packages/riipen-ui-docs/src/pages/components-api/tab.md
- packages/riipen-ui-docs/src/pages/components/form/Error.jsx
- packages/riipen-ui-docs/src/pages/components/form/ErrorScroll.jsx
- packages/riipen-ui-docs/src/pages/components/form/Errors.jsx
- packages/riipen-ui-docs/src/pages/components/form/form.md
- packages/riipen-ui/src/components/Form.jsx
1. Update form component error handling to allow for more types or errors
2. Update form component error scrolling when error pops into existance
3. Update form components doc pages
> [PLT-5098] Form Errors

- packages/riipen-ui-docs/src/pages/components/input/Color.jsx
- packages/riipen-ui-docs/src/pages/components/input/input.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Input.jsx
- packages/riipen-ui/src/components/InputHint.jsx
- packages/riipen-ui/src/components/InputLabel.jsx
> Input label color

- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Avatar.jsx
Hopefully last pr...
Update avatar component to set min/max widths/height so that avatar doesn't collapse in with margins/other styling (seen in staging currently in course cards).
Prevents this:
> Add min/max width/height to Avatar component

- packages/riipen-ui-docs/src/pages/components/input/Weight.jsx
- packages/riipen-ui-docs/src/pages/components/input/input.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Input.jsx
- packages/riipen-ui/src/components/InputLabel.jsx
Add text style options to InputLabel
> Input label style

- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Badge.jsx
Add letter-spacing: 0 and update padding to fix some styling bugs for Badge at small size.
components/Badge
> Fix badge css for small size

- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
> bump ui version

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Form.jsx
1. Convert Form to function component
This is pretty much all thats needed to scroll properly when the error actually gets passed into this component properly.
Validation errors do not however (as they happen sync on the fields themselves, while the input is being changed)
Debouncing doesnt really solve the issue (just delays it) so this might be "good enough" to solve the scrolling issue at least
> [PLT-5804] Refactor Form into function component

- packages/riipen-ui-docs/audit-ci.json
- packages/riipen-ui-docs/package-lock.json
- packages/riipen-ui-docs/package.json
> Fix ci audit

- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
> bump version

- packages/riipen-ui/src/components/Container.jsx
Add more defined border to container when border prop is specified.
components/Container
> Update container border

- packages/riipen-ui-docs/package-lock.json
- packages/riipen-ui-docs/package.json
- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
Bump UI version to 0.1.24
package.json
> Bump ui version to 0.1.24

- .circleci/config.yml
> [PLT-5943] Add dockerhub auth to circleci

- packages/riipen-ui/src/components/Accordion.jsx
Add useEffect to accordion to update expanded state if defaultExpanded changes.
components/Accordion
> Add useEffect to update expanded when defaultExpanded changes

- package-lock.json
- packages/riipen-ui-docs/package-lock.json
- packages/riipen-ui-docs/package.json
- packages/riipen-ui-docs/src/pages/components/typography/Color.jsx
- packages/riipen-ui-docs/src/pages/components/typography/Component.jsx
- packages/riipen-ui-docs/src/pages/components/typography/FontWeight.jsx
- packages/riipen-ui-docs/src/pages/components/typography/typography.md
- packages/riipen-ui/src/components/Tab.jsx
- packages/riipen-ui/src/components/Typography.jsx
- packages/riipen-ui/src/themes/default.js
PLT-6185
1. Updated typography to spec
2. Updated docs
Key highlight ares:
1. Typography variant "caption" removed
2. Typography variant "subtitle1" removed
3 Typography variant "subtitle2" removed
4. Typography variant "button" removed
5. Added `fontWeight` as a prop for Typography
- `<Typography>` component
> [PLT-6185] Typography Update

- packages/riipen-ui-docs/pages/components-api/radio-button-group.jsx
- packages/riipen-ui-docs/pages/components-api/radio-button.jsx
- packages/riipen-ui-docs/src/pages/components-api/radio-button-group.md
- packages/riipen-ui-docs/src/pages/components-api/radio-button.md
- packages/riipen-ui-docs/src/pages/components/radio/Button.jsx
- packages/riipen-ui-docs/src/pages/components/radio/radio.md
- packages/riipen-ui/src/components/RadioButton.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.jsx
- packages/riipen-ui/src/components/index.js
[PLT-6320](https://riipen.atlassian.net/browse/PLT-6320)
packages/riipen-ui/src/components/RadioButton.jsx
> [PLT-6320] Added radio buttons and groups

- packages/riipen-ui-docs/src/pages/components/typography/Color.jsx
- packages/riipen-ui/src/components/Checkbox.jsx
- packages/riipen-ui/src/components/Typography.jsx
1. Fix for placement of checkbox clickable area
2. Added `white` and `black` color options to `<Typography>`
> Checkbox & Typography

- packages/riipen-ui/src/components/RadioButton.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.jsx
Filter null children from Radio Button Groups
Fixed type for Radio Button label
1st one fixes issue as follows
```
<RadioButtonGroup>
{false && (
<RadioButton
label={<I18nMessage id="general.requests" />}
value="request"
/>
)}
<RadioButton
label={<I18nMessage id="general.projects" />}
value="project"
/>
<RadioButton
label={<I18nMessage id="general.teams" />}
value="team"
/>
</RadioButtonGroup>
```
> Fixed a couple small issues in new Radio Button and Group

- README.md
- package-lock.json
Updated readme to help new developers
> Updated README

- README.md
- package-lock.json
1. Updated README to help new developers
> [PLT-6727] Readme Updates

- packages/riipen-ui-docs/src/pages/components/chip/Icon.jsx
- packages/riipen-ui-docs/src/pages/components/chip/chip.md
- packages/riipen-ui/jest.config.js
- packages/riipen-ui/src/components/AccordionDetails.test.jsx
- packages/riipen-ui/src/components/Chip.jsx
- packages/riipen-ui/src/components/Chip.test.jsx
- packages/riipen-ui/src/components/__snapshots__/AccordionDetails.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Chip.test.jsx.snap
- packages/riipen-ui/test/setup.js
Removed onIconClick from Chip component because its not used anymore
> remove onIconClick prop from Chip

- packages/riipen-ui/src/components/Chip.test.jsx
- removed afterEach because it runs in setup.js instead
- removed some tests that got duplicated
chip.test.jsx
> fixed chip tests after git branch issues

- packages/riipen-ui/package-lock.json
- packages/riipen-ui/src/components/Backdrop.jsx
- packages/riipen-ui/src/components/Backdrop.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Backdrop.test.jsx.snap
Unit tests for Backdrop
Backdrop.test.jsx
> [PLT-6626] Unit tests for Backdrop

- packages/riipen-ui/src/components/Avatar.jsx
- packages/riipen-ui/src/components/Avatar.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Avatar.test.jsx.snap
Unit tests for Avatar Component
Looking for feedback on alt and src prop tests
Avatar.test.jsx in components folder
> [PLT-6625] Unit tests for Avatar

- packages/riipen-ui/src/components/Divider.jsx
- packages/riipen-ui/src/components/Divider.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Divider.test.jsx.snap
> [PLT-6637] tests for Divider component

- packages/riipen-ui/src/components/ClickAway.jsx
- packages/riipen-ui/src/components/Drawer.jsx
- packages/riipen-ui/src/components/Drawer.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Drawer.test.jsx.snap
> [PLT-6638] tests for Drawer component

- packages/riipen-ui-docs/src/pages/components/badge/badge.md
- packages/riipen-ui/src/components/Badge.jsx
- packages/riipen-ui/src/components/Badge.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Badge.test.jsx.snap
Unit tests for Badge 
Found a spelling error in the docs markdown file 
Badge.test.jsx in the riipen-ui components folder
badge.md in the riipen-ui-docs components folder
> [PLT-6627] Unit Tests for Badge

- packages/riipen-ui/src/components/Banner.jsx
- packages/riipen-ui/src/components/Banner.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Banner.test.jsx.snap
- tests for the Banner component
- height and src props are put into inline styles, instead of in the css
Banner.jsx
Banner.test.jsx
> [PLT-6628] Banner component tests and inline style

- packages/riipen-ui/src/components/Container.jsx
- packages/riipen-ui/src/components/Container.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Container.test.jsx.snap
Added unit tests and added style attribute for the Container component.
Container.jsx in components folder
> [PLT-6636] Unit Tests for Container

- packages/riipen-ui/src/components/List.test.jsx
- packages/riipen-ui/src/components/__snapshots__/List.test.jsx.snap
Unit tests for List component
List.test.jsx
> [PLT-6648] Unit tests for List

- packages/riipen-ui/src/components/ListItem.jsx
- packages/riipen-ui/src/components/MenuItem.jsx
- packages/riipen-ui/src/components/MenuItem.test.jsx
- packages/riipen-ui/src/components/__snapshots__/MenuItem.test.jsx.snap
- tests for MenuItem component
- changed the way color prop is used in ListItem to use the default color when an invalid value is passed in
- ListItem.jsx on line 67
- MenuItem.test.jsx
> [plt-6651] unit tests for MenuItem

- packages/riipen-ui/src/components/Toolbar.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Toolbar.test.jsx.snap
tests for Toolbar component
Toolbar.test.jsx
> [plt-6669] tests for Toolbar component

- packages/riipen-ui/src/components/FormGroup.test.jsx
- packages/riipen-ui/src/components/__snapshots__/FormGroup.test.jsx.snap
Unit tests for FormGroup component
FormGroup.test.jsx
> [PLT-6640] Unit tests for FormGroup

- packages/riipen-ui/src/components/ProgressBar.jsx
- packages/riipen-ui/src/components/ProgressBar.test.jsx
- packages/riipen-ui/src/components/__snapshots__/ProgressBar.test.jsx.snap
tests for ProgressBar component
ProgressBar.test.jsx
> [plt-6655] tests for ProgressBar component

- packages/riipen-ui/src/components/InputHint.test.jsx
- packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
tests for InputHint component
InputHint.test.jsx
> [plt-6645] tests for InputHint component

- packages/riipen-ui/src/components/InputHint.jsx
- packages/riipen-ui/src/components/InputLabel.test.jsx
- packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap
- InputLabel.test.jsx
- InputHint also takes color "black"
> [plt-6646] tests for InputLabel component

- packages/riipen-ui/src/components/Notice.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Notice.test.jsx.snap
> [plt-6654] tests for Notice component

- packages/riipen-ui/src/components/AccordionDetails.test.jsx
- packages/riipen-ui/src/components/AppBar.test.jsx
- packages/riipen-ui/src/components/Avatar.test.jsx
- packages/riipen-ui/src/components/Backdrop.test.jsx
- packages/riipen-ui/src/components/Badge.test.jsx
- packages/riipen-ui/src/components/Banner.test.jsx
- packages/riipen-ui/src/components/Breadcrumbs.test.jsx
- packages/riipen-ui/src/components/Chip.test.jsx
- packages/riipen-ui/src/components/Container.test.jsx
- packages/riipen-ui/src/components/Divider.test.jsx
- packages/riipen-ui/src/components/Drawer.test.jsx
- packages/riipen-ui/src/components/FormGroup.test.jsx
- packages/riipen-ui/src/components/List.test.jsx
- packages/riipen-ui/src/components/MenuItem.test.jsx
- packages/riipen-ui/src/components/ProgressBar.test.jsx
- packages/riipen-ui/src/components/Toolbar.test.jsx
- packages/riipen-ui/src/components/__snapshots__/AccordionDetails.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/AppBar.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Avatar.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Backdrop.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Badge.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Chip.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Container.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Divider.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/MenuItem.test.jsx.snap
Updating tests that we've already completed
> Test conventions

- packages/riipen-ui/src/components/Spinner.jsx
- packages/riipen-ui/src/components/Spinner.test.jsx
- packages/riipen-ui/src/components/__snapshots__/MenuItem.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Spinner.test.jsx.snap
Unit Tests for Spinner
Spinner.test.jsx
> [PLT-6660] Unit Tests for Spinner

- packages/riipen-ui/src/components/Hidden.jsx
- packages/riipen-ui/src/components/Hidden.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Hidden.test.jsx.snap
- tests for Hidden component
- clarified description for the direction prop
Interested to see if classes prop tests are okay because there isn't an explicit classes prop, even though it still allows classes to be passed in.
> [PLT-6643] tests for Hidden component

- packages/riipen-ui/src/components/Typography.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap
> [PLT-6670] tests for typography component

- packages/riipen-ui/src/components/Radio.test.jsx
- packages/riipen-ui/src/components/__snapshots__/MenuItem.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
Unit tests for Radio
Tests are passing, but need to look in to the warning message that appears to relate to RadioGroup's onChange prop. The warning message notes that the checked prop appears to require an onChange handler when used.
Radio.test.jsx
> [PLT-6656] Unit tests for Radio

- packages/riipen-ui/src/components/Tabs.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Tabs.test.jsx.snap
> [PLT-6668] tests for Tabs component

- packages/riipen-ui/src/components/RadioGroup.jsx
- packages/riipen-ui/src/components/RadioGroup.test.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioGroup.test.jsx.snap
tests for RadioGroup component
> [PLT-6659] tests for RadioGroup component

- packages/riipen-ui/src/components/RadioButtonGroup.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.test.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
- Tests for RadioButtonGroup component
- children prop changed to required
RadioButtonGroup.test.jsx
> [PLT-6658] Tests for RadioButtonGroup component

- packages/riipen-ui/src/components/Tab.jsx
- packages/riipen-ui/src/components/Tab.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap
Unit Tests for Tab
Default props are not formatted the same as the other components, had to adjust that test.
Tab.test.jsx
> [PLT-6661] Unit Tests for Tab

- packages/riipen-ui/src/components/TableBody.test.jsx
- packages/riipen-ui/src/components/__snapshots__/TableBody.test.jsx.snap
Unit Tests for TableBody
<tbody> has special requirements for usage, so both <td> and <tr> were required for the children prop test
TableBody.test.jsx
> [PLT-6663] Unit Tests for TableBody

- packages/riipen-ui/src/components/Spinner.test.jsx
- packages/riipen-ui/src/components/TableCell.jsx
- packages/riipen-ui/src/components/TableCell.test.jsx
- packages/riipen-ui/src/components/__snapshots__/TableCell.test.jsx.snap
Unit tests for TableCell, space convention change for Spinner
TableCell.test.jsx
> [PLT-6664] Unit tests for TableCell

- packages/riipen-ui/src/components/TableHeaderCell.jsx
- packages/riipen-ui/src/components/TableHeaderCell.test.jsx
- packages/riipen-ui/src/components/__snapshots__/TableHeaderCell.test.jsx.snap
- tests for TableHeaderCell
- changed component to use inline style for textAlign
> [PLT-6666} tests for TableHeaderCell

- packages/riipen-ui/src/components/TableHeader.test.jsx
- packages/riipen-ui/src/components/__snapshots__/TableHeader.test.jsx.snap
> [PLT-6665] tests for TableHeader component

- packages/riipen-ui/src/components/RadioButton.test.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
Unit Tests for RadioButton
RadioButton.test.jsx
> [PLT-6657] Unit Tests for RadioButton

- packages/riipen-ui/src/components/Accordion.test.jsx
- packages/riipen-ui/src/components/AccordionSummary.jsx
- packages/riipen-ui/src/components/__snapshots__/Accordion.test.jsx.snap
- tests for the Accordion component
- focus, blur, focusVisible removed from AccordionSummary
> [Plt-6621] tests for Accordion component

- packages/riipen-ui/src/components/ButtonIcon.jsx
- packages/riipen-ui/src/components/ButtonIcon.test.jsx
- packages/riipen-ui/src/components/__snapshots__/ButtonIcon.test.jsx.snap
- outline prop removed from ButtonIcon because it doesn't do anything anymore
- tests in ButtonIcon.test.jsx
> [PLT-6631] tests for ButtonIcon component

- package-lock.json
- packages/riipen-ui/src/components/AccordionSummary.test.jsx
- packages/riipen-ui/src/components/__snapshots__/AccordionSummary.test.jsx.snap
Tests for AccordionSummary
Warning for onFocusVisible appears but all tests pass. Once Accordion is merged with master, should be able to run without the warning.
AccordionSummary.test.jsx
> [PLT-6623] Tests for AccordionSummary

- packages/riipen-ui/src/components/Input.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap
Tests for Input
Input.test.jsx
> [PLT-6644] Tests for Input

- packages/riipen-ui/src/components/ClickAway.jsx
- packages/riipen-ui/src/components/ClickAway.test.jsx
- packages/riipen-ui/src/components/__snapshots__/ClickAway.test.jsx.snap
- tests for ClickAway component
- checking for null children before cloneElement
> [Plt-6634] tests for ClickAway component

- packages/riipen-ui/src/components/ListItem.test.jsx
- packages/riipen-ui/src/components/__snapshots__/ListItem.test.jsx.snap
> [PLT-6649] tests for ListItem component

- packages/riipen-ui/src/components/Link.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Link.test.jsx.snap
- Tests for Link component
- the underline prop is not testable :(
> [PLT-6647] Tests for Link component

- .npmrc
- package-lock.json
- packages/riipen-ui-docs/src/pages/components/grid/Static.jsx
- packages/riipen-ui/package-lock.json
- packages/riipen-ui/src/components/Banner.jsx
- packages/riipen-ui/src/components/Banner.test.jsx
- packages/riipen-ui/src/components/Container.jsx
- packages/riipen-ui/src/components/Container.test.jsx
- packages/riipen-ui/src/components/GridItem.jsx
- packages/riipen-ui/src/components/GridItem.test.jsx
- packages/riipen-ui/src/components/TableCell.jsx
- packages/riipen-ui/src/components/TableCell.test.jsx
- packages/riipen-ui/src/components/TableHeaderCell.jsx
- packages/riipen-ui/src/components/TableHeaderCell.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Banner.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Container.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/GridItem.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/TableCell.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/TableHeaderCell.test.jsx.snap
1. Removed inline styles from components
2. Updates tests to change how we test inline styles
3. Had to update all the snapshots for components I edited to accommodate no more inline styles
> Inline Styles

- packages/riipen-ui/src/components/Table.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Table.test.jsx.snap
Tests for Table component
The `forwardedRef` prop sets the `ref` of the `<table>` element. `ref` itself is React implemented and does not show up when the component mounts.
> [PLT-6662] Tests for Table component

- packages/riipen-ui/src/components/TableRow.test.jsx
- packages/riipen-ui/src/components/__snapshots__/TableRow.test.jsx.snap
Tests for TableRow
TableRow.test.jsx
> [PLT-6667] Tests for TableRow

- packages/riipen-ui/src/components/NoSSR.test.jsx
- packages/riipen-ui/src/components/__snapshots__/NoSSR.test.jsx.snap
> [PLT-6653] Tests for NoSSR component

- packages/riipen-ui/src/components/Grid.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Grid.test.jsx.snap
> [PLT-6641] Tests for Grid

- packages/riipen-ui/src/components/Form.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Form.test.jsx.snap
Tests for Form
Tried testing the errorScroll and enter props with mock & spy functions, but could not find a test that worked with functional components.
Form.test.jsx
> [PLT-6639] Tests for Form

- package-lock.json
- packages/riipen-ui-docs/pages/components-api/switch.jsx
- packages/riipen-ui-docs/pages/components/switch.jsx
- packages/riipen-ui-docs/src/pages.js
- packages/riipen-ui-docs/src/pages/components-api/paper.md
- packages/riipen-ui-docs/src/pages/components-api/switch.md
- packages/riipen-ui-docs/src/pages/components/switch/Basic.jsx
- packages/riipen-ui-docs/src/pages/components/switch/Size.jsx
- packages/riipen-ui-docs/src/pages/components/switch/switch.md
- packages/riipen-ui/src/components/Switch.jsx
- packages/riipen-ui/src/components/Switch.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Switch.test.jsx.snap
- packages/riipen-ui/src/components/index.js
Started on a fresh branch because I had some git issues with the first one.
> [PLT-7072] Add switch component (2)

- package-lock.json
- package.json
Upgrade lerna to get rid of dependency with vulnerability. Dont think there are any breaking changes
https://github.com/lerna/lerna/releases
> upgrade lerna

- packages/riipen-ui-docs/src/pages/components/button/Icons.jsx
- packages/riipen-ui/src/components/AccordionSummary.test.jsx
- packages/riipen-ui/src/components/ButtonIcon.jsx
- packages/riipen-ui/src/components/ButtonIcon.test.jsx
- packages/riipen-ui/src/components/__snapshots__/ButtonIcon.test.jsx.snap
1. Added outlined variant to ButtonIcon
> [PLT-7150] ButtonIcon Variants

- packages/riipen-ui-docs/src/pages/components/typography/TextTransform.jsx
- packages/riipen-ui-docs/src/pages/components/typography/typography.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Typography.jsx
- packages/riipen-ui/src/components/Typography.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap
Add textTransform prop to Typography
> Text transform

- packages/riipen-ui/package-lock.json
- packages/riipen-ui/package.json
> Bump ui version to 0.4.13

- packages/riipen-ui-docs/src/pages/components/paper/Elevation.jsx
- packages/riipen-ui-docs/src/pages/components/paper/Outline.jsx
- packages/riipen-ui-docs/src/pages/components/paper/Rounded.jsx
- packages/riipen-ui/src/components/Paper.jsx
- packages/riipen-ui/src/components/__snapshots__/Paper.test.jsx.snap
1. Switch the `<Paper>` component to use default CSS `display` attribute per component.
> [PLT-7268] Paper Block

- packages/riipen-ui-docs/src/pages/components/input/Adornments.jsx
- packages/riipen-ui/src/components/Input.jsx
- packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap
Minor touch up to Input start/end adornment spacing.
> Upate adornment spacing

- packages/riipen-ui-docs/src/pages/components/radio/Button.jsx
- packages/riipen-ui-docs/src/pages/components/radio/ButtonColor.jsx
- packages/riipen-ui-docs/src/pages/components/radio/ButtonSize.jsx
- packages/riipen-ui-docs/src/pages/components/radio/ButtonVariant.jsx
- packages/riipen-ui-docs/src/pages/components/radio/radio.md
- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/Input.jsx
- packages/riipen-ui/src/components/RadioButton.jsx
- packages/riipen-ui/src/components/RadioButton.test.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.test.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
Update Radio Button and Radio Button Group.
1. Add new variants to button group
2. Add colors to radio button
3. Add size to radio button
> Radio button

- packages/riipen-ui-docs/src/pages/components/chip/Colors.jsx
- packages/riipen-ui-docs/src/pages/components/chip/Disabled.jsx
- packages/riipen-ui-docs/src/pages/components/chip/Hover.jsx
- packages/riipen-ui-docs/src/pages/components/chip/Variants.jsx
- packages/riipen-ui/src/components/Chip.jsx
- packages/riipen-ui/src/components/Chip.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Chip.test.jsx.snap
1. Updated chip grey colors available
2. Updated chip disabled styles
3. Updated chip focus styles
4. Updated chip clickable styles
5. Updated tests / docs for chip
The chip component. It's pretty heavily refactored to might be best to just examine the whole file rather than the diff.
> Chip Styles

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/RadioButton.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.jsx
- packages/riipen-ui/src/components/RadioGroup.jsx
- packages/riipen-ui/src/components/RadioGroup.test.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioGroup.test.jsx.snap
> Radio button cleanup

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/RadioButtonGroup.jsx
- packages/riipen-ui/src/components/RadioGroup.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
Fix passing busted name prop in radio groups
> Fix name prop in radio groups

- packages/riipen-ui-docs/src/pages/components/radio/Button.jsx
- packages/riipen-ui-docs/src/pages/components/radio/Usage.jsx
- packages/riipen-ui/src/components/RadioGroup.jsx
> Fix radio group passing id to children radio buttons

- packages/riipen-ui/package.json
- packages/riipen-ui/src/components/TableGenerator.jsx
> Fix table not taking up full width

- packages/riipen-ui/src/components/Tooltip.jsx
- packages/riipen-ui/src/components/Tooltip.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Tooltip.test.jsx.snap
Update Tooltip so that it is a function component.
Add tests + snapshots.
Updating to a function component seems to have fixed the Samsung focus bug.
components/Tooltip
> Convert Tooltip to Function Component and Add Unit Tests

- packages/riipen-ui/src/components/Popover.jsx
- packages/riipen-ui/src/components/Popover.test.jsx
- packages/riipen-ui/src/components/Tooltip.jsx
- packages/riipen-ui/src/components/Tooltip.test.jsx
- packages/riipen-ui/src/components/__snapshots__/Menu.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Popover.test.jsx.snap
Convert Popover to be a function component.
Add basic test file.
TODO: Beef up tests.
components/Popover
> Convert Popover to function component

- packages/riipen-ui/README.md
- packages/riipen-ui/scripts/release.sh
Update `script/release.sh` script to make sure the first param is passed. Also, update `README.md` to reflect the change.
> Update release bash script to ensure the first param is passed

- packages/riipen-ui/src/components/Drawer.test.jsx
- packages/riipen-ui/src/components/Input.test.jsx
- packages/riipen-ui/src/components/Link.test.jsx
- packages/riipen-ui/src/components/Menu.test.jsx
- packages/riipen-ui/src/components/MenuItem.test.jsx
- packages/riipen-ui/src/components/MenuList.test.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.test.jsx
- packages/riipen-ui/src/components/RadioGroup.test.jsx
- packages/riipen-ui/src/components/Switch.test.jsx
- packages/riipen-ui/src/components/Tab.test.jsx
- packages/riipen-ui/src/components/Tabs.test.jsx
Update rest of ui kit tests to use invoke instead of simulate.
> [PLT-8291]: Update tests to use invoke instead of simulate 

- packages/riipen-ui/src/components/Accordion.test.jsx
- packages/riipen-ui/src/components/Button.test.jsx
- packages/riipen-ui/src/components/ButtonIcon.test.jsx
- packages/riipen-ui/src/components/Checkbox.test.jsx
- packages/riipen-ui/src/components/Chip.test.jsx
- packages/riipen-ui/src/components/ClickAway.test.jsx
- packages/riipen-ui/src/components/Drawer.test.jsx
- packages/riipen-ui/src/components/Input.test.jsx
- packages/riipen-ui/src/components/Link.test.jsx
- packages/riipen-ui/src/components/Menu.test.jsx
- packages/riipen-ui/src/components/MenuItem.test.jsx
- packages/riipen-ui/src/components/MenuList.test.jsx
- packages/riipen-ui/src/components/RadioButtonGroup.test.jsx
- packages/riipen-ui/src/components/RadioGroup.test.jsx
- packages/riipen-ui/src/components/Switch.test.jsx
- packages/riipen-ui/src/components/Tab.test.jsx
- packages/riipen-ui/src/components/Tabs.test.jsx
- packages/riipen-ui/src/components/Tooltip.test.jsx
Update tests to use invoke instead of simulate.
> [PLT-8291]: Update unit tests to use invoke 

- packages/riipen-ui/src/components/Input.jsx
Forgot to pass on the event object to these event handler props. :(
> Make sure to pass on the event object to onFocus & onBlur props in Input

- packages/riipen-ui/src/components/TableGenerator.jsx
- packages/riipen-ui/src/components/TableGenerator.test.jsx
- packages/riipen-ui/src/components/__snapshots__/TableGenerator.test.jsx.snap
> Fix table generator

- packages/riipen-ui/src/components/Button.jsx
- packages/riipen-ui/src/components/__snapshots__/Button.test.jsx.snap
Update button to have word break normal so it isn't affected by any other word breaks.
button component
> Make word break normal

- packages/riipen-ui/src/components/Button.jsx
- packages/riipen-ui/src/components/Tab.jsx
- packages/riipen-ui/src/components/__snapshots__/Button.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/ButtonIcon.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Chip.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Link.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/ListItem.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap
- packages/riipen-ui/src/themes/default.js
https://riipen.atlassian.net/browse/PLT-8331
Some corrections for Tabs and Button fonts in mobile
This PR is related to web PR https://github.com/riipen/platform-web/pull/4866
> [PLT-8331] corrections for Tabs and Button fonts in mobile

- packages/riipen-ui/src/components/Switch.jsx
- packages/riipen-ui/src/components/__snapshots__/Switch.test.jsx.snap
> [PLT-8986] Make switch disabled colour less dark

- packages/riipen-ui-docs/pages/components-api/vertical-divider.jsx
- packages/riipen-ui-docs/pages/components/vertical-divider.jsx
- packages/riipen-ui-docs/src/pages.js
- packages/riipen-ui-docs/src/pages/components-api/tab.md
- packages/riipen-ui-docs/src/pages/components-api/tabs.md
- packages/riipen-ui-docs/src/pages/components-api/vertical-divider.md
- packages/riipen-ui-docs/src/pages/components/vertical-divider/Spacing.jsx
- packages/riipen-ui-docs/src/pages/components/vertical-divider/vertical-divider.md
- packages/riipen-ui/src/components/VerticalDivider.jsx
- packages/riipen-ui/src/components/VerticalDivider.test.jsx
- packages/riipen-ui/src/components/__snapshots__/VerticalDivider.test.jsx.snap
Add new vertical divider component and update component and api pages
[PLT-8964](https://riipen.atlassian.net/browse/PLT-8964)
After running npm start at the root
http://localhost:3000/components/vertical-divider/
http://localhost:3000/components-api/vertical-divider/
> [PLT-8964] Add new vertical divider component

- .circleci/config.yml
Update aws-cli orb version in `.circleci/config.yml` and replace /install & /configure steps with aws-cli/setup for `docs` job
> Update aws-cli orb version in .circleci/config.yml

- .circleci/config.yml
Remove python libs install steps in the docs job cause they are not needed anymore.
> Remove python libs install steps in .circleci/config.yml

- .circleci/config.yml
Update s3 bucket path to more explicit one which is s3://ui-production-docs
> Update s3 bucket path to more explicit one

- packages/riipen-ui/src/components/__snapshots__/Breadcrumbs.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Button.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/ButtonIcon.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Checkbox.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Chip.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Container.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Hidden.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Input.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/InputHint.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/InputLabel.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Link.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/ListItem.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Radio.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Tab.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/Typography.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/VerticalDivider.test.jsx.snap
- packages/riipen-ui/src/themes/default.js
Update device breakpoints to the most commonly used
In order to match web PR https://github.com/riipen/platform-web/pull/4951
https://www.figma.com/file/RYjBuSngR9y0L5PeDZp6b2/01-Components?node-id=1633%3A373523
https://riipen.atlassian.net/browse/PLT-8333
> [PLT-8333] Update device breakpoints

- packages/riipen-ui/src/components/RadioButton.jsx
- packages/riipen-ui/src/components/__snapshots__/RadioButton.test.jsx.snap
- packages/riipen-ui/src/components/__snapshots__/RadioButtonGroup.test.jsx.snap
Issue: fixed radio button width size make long label text jump a line.
- Remove fixed width size from RadioButton
- Fix RadioButton font medium size
> [[PLT-9619] Remove fixed width size from RadioButton

- packages/riipen-ui-docs/config/ansible/make.yml
- packages/riipen-ui-docs/config/ansible/template.yml
Update cloudformation stack name parameters
> [PLT-9350] Update cloudformation stack name parameters
